# Generated by Django 3.1.3 on 2022-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220211_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='stock_firm',
            field=models.CharField(choices=[('키움증권', 'KIWOOM'), ('삼성증권', 'SAMSUNG'), ('한국투자증권', 'KOREA'), ('KB증권', 'KOOKMIN'), ('NH투자증권', 'NONGHYUP'), ('미래에셋증권', 'MIREA'), ('신한금융투자', 'SHINHAN'), ('그 외', 'ETC')], max_length=10),
        ),
    ]
