# Generated by Django 3.1.3 on 2022-02-13 09:13

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20220211_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'A user with that nickname already exists.'}, help_text='Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=10, unique=True, validators=[common.models.UnicodeNicknameValidator()], verbose_name='nickname'),
        ),
    ]
