# Generated by Django 3.1.3 on 2022-02-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20220213_1813'),
        ('common', '0006_alter_profile_id'),
    ]

    operations = [
    ]
