# Generated by Django 4.0.2 on 2022-02-15 01:35

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20220214_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'A user with that nickname already exists.'}, help_text='Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=10, validators=[common.models.UnicodeNicknameValidator()], verbose_name='nickname'),
        ),
    ]
