# Generated by Django 3.1.3 on 2022-02-04 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='voter',
            field=models.ManyToManyField(related_name='voter_discussion', to=settings.AUTH_USER_MODEL),
        ),
    ]
