# Generated by Django 3.1.3 on 2022-02-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220207_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='hitting',
        ),
        migrations.AddField(
            model_name='discussion',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
