# Generated by Django 3.1.3 on 2022-02-04 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20220204_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_discussion', to='auth.user'),
            preserve_default=False,
        ),
    ]
