# Generated by Django 3.1.3 on 2022-02-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_discussion_author'),
        ('board', '0002_alter_answer_id_alter_discussion_id'),
    ]

    operations = [
    ]
