# Generated by Django 4.0.2 on 2022-02-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_discussion_author'),
        ('board', '0003_remove_discussion_author_answer_author_and_more'),
    ]

    operations = [
    ]
