# Generated by Django 4.0.2 on 2022-02-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_answer_id_alter_discussion_id'),
        ('board', '0003_discussion_author'),
    ]

    operations = [
    ]
