# Generated by Django 4.0.2 on 2022-02-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_merge_20220204_1133'),
        ('board', '0005_auto_20220204_1131'),
    ]

    operations = [
    ]
