# Generated by Django 3.1.3 on 2022-02-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20220204_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='hit',
            new_name='hitting',
        ),
    ]
