# Generated by Django 4.0.2 on 2022-02-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_merge_20220204_1439'),
        ('board', '0006_merge_20220204_1535'),
        ('board', '0008_auto_20220204_1421'),
    ]

    operations = [
    ]
